#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)


cat <<EOF
Welcome in the Amstrad CPC Crossdev machine

${bold}INSTALLED TOOLS${normal}

${bold}PC related${normal}
EOF

cat  <<EOF

 - Arkos Tracker 2
 - Arnold emulator
 - grafx2
 - git
 - meld
EOF

cat <<EOF

${bold}CPC related${normal}
EOF

cat <<EOF

 - cpctelera
 - exomizer
 - createSnapshot
 - hxcfe
 - hideur
 - iDSK
 - libdsk
 - rasm
 - vasm
 - vlink
 - z80tonops
EOF

cat <<EOF

Contact Krusty/Benediction if other tools are needed
EOF



export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

